### ISSUE TITLE
Robot Account: does not work

### ISSUE THREAD

**Issue by suportgc** [clonemeagain/plugin-autocloser#14]
Hi friend, good evening.

I would like your help with a problem.

I select the analyst for Robot, save and when I leave the page the plugin and return, the analyst is no longer selected

follow print
http://prntscr.com/gtt8iv
http://prntscr.com/gtt8mh

**Comment by clonemeagain** [comment]
Are you getting any logged errors? Which version of osticket are you using?

**Comment by suportgc** [comment]
Hello, I did not receive any logs.
Unable to send reply, no assigned Agent on ticket, and no Robot account specified in config.

Version
v1.10.1 (9ae093d) - Updated

**Comment by clonemeagain** [comment]
v1.10.1 ah.. I haven't tested it with that yet. Might be different. I'll get onto it tonight and get back to you.

**Comment by suportgc** [comment]
Thank you very much, my friend.

Congratulations on the excellent plugin

**Comment by clonemeagain** [comment]
Hmm, does it keep working? Because it looks like an API change in osTicket that results in Staff::getName() returning an object instead of a string. 

Which caused my plugin to store: 
```json
{"1":{"format":"full","parts":{"first":"Griz","last":"Ly"},"name":"Griz Ly"}}  
```
instead of
```json 
 {"1":"Griz Ly"} 
```
So, the "display" part didn't work properly.  I think.  It didn't change it on my end after upgrading, but 

Patched that, and tested, it seems to work for me mate, can you try the patch?

**Comment by suportgc** [comment]
Solved

**Comment by clonemeagain** [comment]
Received report that the same problem is happening with the canned response, so I'm reopening this to remind me to check it.

**Comment by clonemeagain** [comment]
Ok, can't be the same issue, as I use their method to get the canned responses. 
Might be a config table issue.. which seems to be corrected by uninstalling the plugin (delete), then install it. The delete process just deletes the config.

**Comment by suportgc** [comment]
Hello Friend.
Really after reinstalling the plugin the error has been solved.

Thank you very much for the quick reply.

**Comment by suportgc** [comment]
Hi friend, good evening.

Could you verify ?
After the last update the system stopped working, returning with this error.

I already uninstalled and installed and the error persists

**Comment by clonemeagain** [comment]
I've not updated yet, but I'll have a look when I can.

**Comment by suportgc** [comment]
thank you so much friend you are awesome.
